version: "3"

services:
  mysql:
    container_name: mysql
    image: mysql:5.7
    restart: unless-stopped
    env_file: .env
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - TZ=Asia/Seoul
    volumes:
      - /home/ubuntu/mysql:/var/lib/mysql
      - ./config/mysql/:/etc/mysql/conf.d
    ports:
      - "3306:3306"

volumes:
  mysql:
